catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("thanks/", views.thanks, name="thanks"),
    path("inforequest/", views.info_request, name="info-request"),
    path("corsrequest/", views.cors_request, name="cors-request"),
    path("lessons/", views.LessonListView.as_view(), name="lessons"),
    path("lessons/<int:pk>", views.LessonDetailView.as_view(), name="lesson-detail"),
    path("students/", views.StudentListView.as_view(), name="students"),
    path("students/<int:pk>", views.StudentDetailView.as_view(), name="student-detail"),
    path("teachers/", views.TeacherListView.as_view(), name="teachers"),
    path("types/", views.TypeListView.as_view(), name="types"),
    path("tags/", views.TagListView.as_view(), name="tags"),
    path("lesson/create/", views.LessonCreate.as_view(), name="lesson-create"),
    path("lesson/<int:pk>/update/", views.LessonUpdate.as_view(), name="lesson-update"),
    path("lesson/<int:pk>/delete/", views.LessonDelete.as_view(), name="lesson-delete"),
    path("student/create/", views.StudentCreate.as_view(), name="student-create"),
    path(
        "student/<int:pk>/update/", views.StudentUpdate.as_view(), name="student-update"
    ),
    path(
        "student/<int:pk>/delete/", views.StudentDelete.as_view(), name="student-delete"
    ),
    path("teacher/create/", views.TeacherCreate.as_view(), name="teacher-create"),
    path(
        "teacher/<int:pk>/update/", views.TeacherUpdate.as_view(), name="teacher-update"
    ),
    path(
        "teacher/<int:pk>/delete/", views.TeacherDelete.as_view(), name="teacher-delete"
    ),
    path("type/create/", views.TypeCreate.as_view(), name="type-create"),
    path("type/<int:pk>/update/", views.TypeUpdate.as_view(), name="type-update"),
    path("type/<int:pk>/delete/", views.TypeDelete.as_view(), name="type-delete"),
    path("tag/create/", views.TagCreate.as_view(), name="tag-create"),
    path("tag/<int:pk>/update/", views.TagUpdate.as_view(), name="tag-update"),
    path("tag/<int:pk>/delete/", views.TagDelete.as_view(), name="tag-delete"),
]

scinguistics_archive/urls.py
from django.contrib import admin
from django.urls import path

# Use include() to add paths from applications
from django.urls import include

# Use RedirectView() to redirect the base url to an application
from django.views.generic import RedirectView

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    # applications
    path("catalog/", include("catalog.urls")),
    # redirections
    path("", RedirectView.as_view(url="catalog/", permanent=True)),
    # static files
    *static(settings.STATIC_URL, document_root=settings.STATIC_ROOT),
    # authentication (auth.urls needed for 'LOGOUT_REDIRECT_URL' in settings.py to work properly, used in 'base_generic.html for url logout)
    path("accounts/", include("django.contrib.auth.urls")),
    # django-allauth - for patreon authentication
    path("accounts/", include("allauth.urls")),
    # backblaze b2
    path("", include("django_backblaze_b2.urls")),
]

catalog/models.py
from django.db import models
from django.urls import reverse
from django_backblaze_b2 import BackblazeB2Storage


class Tag(models.Model):
    """Model for lesson tags"""

    name = models.CharField(
        max_length=100, unique=True, help_text="Enter a new tag name"
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]


class Type(models.Model):
    """Model for lesson type (e.g. Voice Feminization)"""

    name = models.CharField(
        max_length=100, unique=True, help_text="Enter a new lesson type"
    )

    def __str__(self):
        return self.name


class Teacher(models.Model):
    """Model for the student name"""

    name = models.CharField(
        max_length=200, unique=True, help_text="Enter a new teacher"
    )

    def __str__(self):
        return self.name


class Student(models.Model):
    """Model for the student name"""

    name = models.CharField(
        max_length=200, unique=True, help_text="Enter a new student"
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        """returns the url to access the record of this student"""
        return reverse("student-detail", args=[str(self.id)])

    class Meta:
        ordering = ["name"]


class Lesson(models.Model):
    """Model for the lesson entry"""

    teacher = models.ForeignKey("Teacher", on_delete=models.PROTECT, null=True)
    student = models.ForeignKey("Student", on_delete=models.PROTECT, null=True)
    type = models.ManyToManyField("Type", help_text="Select a type of lesson")
    tags = models.ManyToManyField("Tag", help_text="Select tags for the lesson")
    date_and_time = models.DateTimeField(
        blank=True,
        null=True,
        unique=True,
        help_text="Date and time of the recording (autofilled from CRAIG/GIARC link)",
    )
    recording = models.FileField(
        blank=True,
        null=True,
        upload_to="uploads",
        storage=BackblazeB2Storage,
        help_text="Recording link from the CDN (autofilled from CRAIG/GIARC link)",
    )

    def __str__(self):
        return f"{self.student}'s lesson with {self.teacher} - {self.date_and_time.isoformat()}"

    def get_recording_stamp(self):
        return f"{self.student}-s_lesson_with_{self.teacher}_-_{int(self.date_and_time.timestamp())}"

    @property
    def recording_processing_filestorage_name(self):
        return f"lesson-recording-{self.date_and_time.isoformat()}"

    def get_absolute_url(self):
        """returns the url to access the record of this lesson"""
        return reverse("lesson-detail", args=[str(self.id)])

    class Meta:
        ordering = ["-date_and_time"]

catalog/views.py
from django.shortcuts import render
from .models import Tag, Type, Teacher, Student, Lesson
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from catalog.forms import TagForm, TypeForm, TeacherForm, StudentForm, LessonCreateForm
from django.contrib.auth.mixins import PermissionRequiredMixin
from urllib.request import urlretrieve, urlopen, Request
import urllib3
from urllib.parse import urlparse
from django import db
import os
import shutil
from zipfile import ZipFile
from django.core.files import File
import time
from django.http import HttpResponseRedirect, HttpResponse
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.exceptions import ValidationError
from django.db.models import ProtectedError
import json

def index(request):
    """Home Page view function"""

    # generate counts
    num_students = Student.objects.all().count()
    num_lessons = Lesson.objects.all().count()

    types = list(Type.objects.all())
    list_num_lessons_per_type = [(type_name, Lesson.objects.filter(type=type_name).count()) for type_name in types]

    # context
    context = {
        'num_students': num_students,
        'num_lessons': num_lessons,
        'list_num_lessons_per_type': list_num_lessons_per_type,
    }

    # render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)

def thanks(request):
    """Thank You Page view function"""

    # # getting Patreon campaign id
    # patreon_request_url = "https://www.patreon.com/api/oauth2/v2/campaigns"
    # headers = {'Authorization': 'Bearer ' + os.environ.get('PATREON_CREATOR_ACCESS_TOKEN')}
    # import requests
    # resp = requests.get(patreon_request_url, headers=headers)
    # campaign_id = resp.json().get('data')[0]['id']
    #
    # # getting Patreon campaign members names
    # headers = {'Authorizatiorequestn': 'Bearer ' + os.environ.get('PATREON_CREATOR_ACCESS_TOKEN')}
    # cursor = ''
    # names = list()
    # while cursor != 'END':
    #     patreon_request_url = f"https://www.patreon.com/api/oauth2/v2/campaigns/{campaign_id}/members?include=address&fields[member]=full_name&page[cursor]={cursor}"
    #     resp = requests.get(patreon_request_url, headers=headers)
    #     try:
    #         cursor = resp.json().get('meta')['pagination']['cursors']['next']
    #     except:
    #         cursor = 'END'
    #     finally:
    #         data = resp.json().get('data')
    #         names.extend([member['attributes']['full_name'] for member in data])
    #
    # # context
    # context = {
    #     'patreon_supporters': sorted(names),
    # }

    return render(request, 'thanks.html')#, context=context)

def info_request(request):
    url = request.META.get('QUERY_STRING').replace('url=', '')
    print("url: ", url)
    if url:
        parsed = urlparse(url)
        rec_n = parsed.path.split('/')[3]

        http = urllib3.PoolManager()
        r = http.request('GET', url, preload_content=False)
        with open(f"{rec_n}.txt", "wb") as out:
            while True:
                data = r.read()
                if not data:
                    break
                out.write(data)
        r.release_conn()

        users = []
        with open(f"{rec_n}.txt", 'rt') as f:
            for line in f.read().split("\n"):
                print(line)
                if ("#" in line) and ("Channel" not in line) and ("Requester" not in line):
                    users.append(line.rsplit(" ", maxsplit=1)[0].strip())

        os.system(f"rm {rec_n}.txt")

        response_data = {'users': users}
        response_status = 200
    else:
        response_data = {'none': None}
        response_status = 204
    print("info: ", response_data)
    return HttpResponse(json.dumps(response_data), status=response_status, content_type="application/json")

def cors_request(request):
    url = request.META.get('QUERY_STRING').replace('url=', '')
    print("url: ", url)
    if url:
        # response_data = urlopen(url)
        # response_data = json.loads(response_data.read())
        http = urllib3.PoolManager()
        response_data = http.request('GET', url)
        response_data = json.loads(response_data.data.decode('utf8'))
        response_status = 200
    else:
        response_data = {'none': None}
        response_status = 204
    print("data: ", response_data)
    return HttpResponse(json.dumps(response_data), status=response_status, content_type="application/json")

# class based views
class LessonListView(LoginRequiredMixin, generic.ListView):
    """Lesson List view function"""

    model = Lesson
    paginate_by = 10

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(LessonListView, self).get_context_data(**kwargs)
        # Add data to the context
        ALL_PROCESSES = [name.replace('.zip', '') for name in os.listdir('.') if 'lesson-recording-' in name]

        context['ALL_PROCESSES'] = ALL_PROCESSES
        context['EMPTY_LIST'] = list()

        return context

class LessonDetailView(LoginRequiredMixin, generic.DetailView):
    """Lesson Detail view function"""

    model = Lesson

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(LessonDetailView, self).get_context_data(**kwargs)
        # Add data to the context
        # set variable
        PROCESSING = False
        # check if files are still present
        file_name = context['lesson'].recording_processing_filestorage_name
        for name in os.listdir('.'):
            if file_name in name:
                PROCESSING = True
        # add variable to context
        context['PROCESSING'] = PROCESSING

        return context

class StudentListView(LoginRequiredMixin, generic.ListView):
    """Student List view function"""

    model = Student
    paginate_by = 10

class StudentDetailView(LoginRequiredMixin, generic.DetailView):
    """Student Detail view function"""

    model = Student

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(StudentDetailView, self).get_context_data(**kwargs)
        # Add data to the context
        context['lesson_list'] = Lesson.objects.filter(student=context['student'])
        return context

class TeacherListView(LoginRequiredMixin, generic.ListView):
    """Teacher List view function"""

    model = Teacher
    paginate_by = 10

class TypeListView(LoginRequiredMixin, generic.ListView):
    """Type List view function"""

    model = Type
    paginate_by = 10

class TagListView(LoginRequiredMixin, generic.ListView):
    """Tag List view function"""

    model = Tag
    paginate_by = 10

# generic editing views
# tag
class TagCreate(PermissionRequiredMixin, CreateView):
    permission_required = 'catalog.add_tag'
    model = Tag
    form_class = TagForm

    def form_valid(self, form):
        tag = form.save(commit=False)
        tag.name = form.cleaned_data.get('name')
        tag.save()

        next = self.request.POST.get('next') or reverse_lazy('tags')
        return HttpResponseRedirect(next)

class TagUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'catalog.change_tag'
    model = Tag
    form_class = TagForm

    def form_valid(self, form):
        tag = form.save(commit=False)
        tag.name = form.cleaned_data.get('name')
        tag.save()

        next = self.request.POST.get('next') or reverse_lazy('tags')
        return HttpResponseRedirect(next)

class TagDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'catalog.delete_tag'
    model = Tag
    success_url = reverse_lazy('tags')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()

        # check if lessons are using the instance
        in_use = list()
        for lesson in Lesson.objects.all():
            in_use.extend([tag.name for tag in lesson.tags.all()])

        print(in_use)
        if self.object.name in in_use:
            context = self.get_context_data(object=self.object, error='Cannot delete in use object instance, delete all uses first')
            return self.render_to_response(context)
        else:
            self.object.delete()

        return HttpResponseRedirect(success_url)

# type
class TypeCreate(PermissionRequiredMixin, CreateView):
    permission_required = 'catalog.add_type'
    model = Type
    form_class = TypeForm

    def form_valid(self, form):
        type = form.save(commit=False)
        type.name = form.cleaned_data.get('name')
        type.save()

        next = self.request.POST.get('next') or reverse_lazy('types')
        return HttpResponseRedirect(next)

class TypeUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = 'catalog.change_type'
    model = Type
    form_class = TypeForm

    def form_valid(self, form):
        type = form.save(commit=False)
        type.name = form.cleaned_data.get('name')
        type.save()

        next = self.request.POST.get('next') or reverse_lazy('types')
        return HttpResponseRedirect(next)

class TypeDelete(PermissionRequiredMixin, DeleteView):
    permission_required = 'catalog.delete_type'
    model = Type
    success_url = reverse_lazy('types')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()

        # check if lessons are using the instance
        in_use = list()
        for lesson in Lesson.objects.all():
            in_use.extend([type.name for type in lesson.types.all()])

        print(in_use)
        if self.object.name in in_use:

catalog/templates/catalog/lesson_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Lesson</h1>

<p>Are you sure you want to delete the lesson: {{ lesson }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

catalog/templates/catalog/lesson_create_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
      <tr class="fieldWrapper">
        <th>{{ form.teacher.label_tag }}</th>
        <td>
            {{ form.teacher.errors }}
            {{ form.teacher }}
            <a href="{% url 'teacher-create' %}" class="btn btn-success btn-sm"><strong>+</strong></a>
            <br>{{ form.teacher.help_text }}
        </td>
      </tr>
      <tr class="fieldWrapper">
        <th>{{ form.student.label_tag }}</th>
        <td>
            {{ form.student.errors }}
            {{ form.student }}
            <a href="{% url 'student-create' %}" class="btn btn-success btn-sm"><strong>+</strong></a>
            <br>{{ form.student.help_text }}
        </td>
      </tr>
      <tr class="fieldWrapper">
        <th>{{ form.type.label_tag }}</th>
        <td>
            {{ form.type.errors }}
            {{ form.type }}
            <a href="{% url 'type-create' %}" class="btn btn-success btn-sm"><strong>+</strong></a>
            <br>{{ form.type.help_text }}
        </td>
      </tr>
      <tr class="fieldWrapper">
        <th>{{ form.tags.label_tag }}</th>
        <td>
            {{ form.tags.errors }}
            {{ form.tags }}
            <a href="{% url 'tag-create' %}?next={{ request.path|urlencode }}" class="btn btn-success btn-sm"><strong>+</strong></a>
            <br>{{ form.tags.help_text }}
        </td>
      </tr>
      <tr>
	<th></th>
	<td><strong>Please, only input a CRAIG/GIARC link OR upload a file (uploading a file requires setting the date and time):</strong></td>
      </tr>
      <tr class="fieldWrapper">
        <th>{{ form.recording_processing_link.label_tag }}</th>
        <td>
            {{ form.recording_processing_link.errors }}
            {{ form.recording_processing_link }}
            <button type="button" onclick="get_info()">get info</button>
            <br>{{ form.recording_processing_link.help_text }}
            <br><label style="color:Green" id=startTime>start time: </label>
            <br><label style="color:Green" id=duration>duration: </label>
            <br><label style="color:Green" id=users>users: </label>
        </td>
      </tr>
      <tr class="fieldWrapper">
        <th>{{ form.form_date_and_time.label_tag }}</th>
        <td>
            {{ form.form_date_and_time.errors }}
            {{ form.form_date_and_time }}
            <br>{{ form.form_date_and_time.help_text }}
        </td>
      </tr>
      <tr class="fieldWrapper">
        <th>{{ form.form_recording_file.label_tag }}</th>
        <td>
            {{ form.form_recording_file.errors }}
            {{ form.form_recording_file }}
            <br>{{ form.form_recording_file.help_text }}
        </td>
      </tr>
    </table>
    {{ form.non_field_errors }}
    <input type="submit" value="Submit">
  </form>

  <script>
      function startTime() {
          var url = document.getElementById("id_recording_processing_link").value;

          const parsed = new URL(url);
          const newurl = `${parsed.protocol}//${parsed.host}/api/v1/recordings/${parsed.pathname.split("/")[2]}?key=${parsed.searchParams.get('key')}`;

          var xhttp = new XMLHttpRequest();
          xhttp.onreadystatechange = function() {
            if (this.readyState == 4 && this.status == 200) {
                var res = JSON.parse(this.responseText);
                var start = res.recording.startTime;

                document.getElementById("startTime").innerHTML = "start time: " + new Date(start).toString();
            } else if (this.readyState == 4 && this.status != 200) {
                document.getElementById("startTime").innerHTML = "start time: NOT FOUND";
            } else {
                document.getElementById("startTime").innerHTML = "start time: loading...";
            }
          };

          xhttp.open("GET", `${window.location.protocol}//${window.location.host}/catalog/corsrequest/?url=${newurl}`, true);
          xhttp.send();
      }

      function duration() {
          var url = document.getElementById("id_recording_processing_link").value;
          const parsed = new URL(url);
          const newurl = `${parsed.protocol}//${parsed.host}/api/v1/recordings/${parsed.pathname.split("/")[2]}/duration?key=${parsed.searchParams.get('key')}`

          var xhttp = new XMLHttpRequest();
          xhttp.onreadystatechange = function() {
            if (this.readyState == 4 && this.status == 200) {
                var dur_s = Math.trunc(JSON.parse(this.responseText).duration);
                var dur_m = Math.trunc(dur_s/60);
                var dur_h = Math.trunc(dur_m/60);
                let is_short = dur_s < 1801;
                const pad = (num) => String(num).padStart(2, '0');
                var dur = `${pad(dur_h)}:${pad(dur_m-(dur_h*60))}:${pad(dur_s-(dur_m*60))}`
                document.getElementById("duration").innerHTML = "duration: " + dur;
                if (is_short) {
                  document.getElementById("duration").style.color = "Orange";
                }
            } else if (this.readyState == 4 && this.status != 200) {
                document.getElementById("duration").innerHTML = "duration: NOT FOUND";
            } else {
                document.getElementById("duration").innerHTML = "duration: loading...";
            }
          };
          xhttp.open("GET", `${window.location.protocol}//${window.location.host}/catalog/corsrequest/?url=${newurl}`, true);
          xhttp.send();
      }
      function users() {
          var url = document.getElementById("id_recording_processing_link").value;
          const parsed = new URL(url);
          const newurl = `${parsed.protocol}//${parsed.host}/api/v1/recordings/${parsed.pathname.split("/")[2]}?key=${parsed.searchParams.get('key')}`

          var xhttp = new XMLHttpRequest();
          xhttp.onreadystatechange = function() {
            if (this.readyState == 4 && this.status == 200) {
                var users = JSON.parse(this.responseText).users;
                var users_list = [];
                for (let i = 0; i < users.length; i++) {
                    users_list.push(users[i].username);
                }
                document.getElementById("users").innerHTML = "users: " + users_list.join(", ");
            } else if (this.readyState == 4 && this.status != 200) {
                document.getElementById("users").innerHTML = "users: NOT FOUND";
            } else {
                document.getElementById("users").innerHTML = "users: loading...";
            }
          };
          xhttp.open("GET", `${window.location.protocol}//${window.location.host}/catalog/corsrequest/?url=${newurl}`, true);
          xhttp.send();
      }
      function get_info() {
          startTime();
          duration();
          users();
      }
  </script>
{% endblock %}

catalog/templates/catalog/lesson_list.html
{% extends "base_generic.html" %}

{% block extra_head %}
  {% if ALL_PROCESSES != EMPTY_LIST %}
    <meta http-equiv="refresh" content="60">
  {% endif %}
{% endblock %}

{% block content %}
  <h1>Lesson List</h1>
  <hr>
  {% if perms.catalog.add_lesson %}
  <h2>Staff: <a href="{% url 'lesson-create' %}" class="btn btn-success">Create New Lesson Record</a></h2>
  <hr>
  {% endif %}
  {% if lesson_list %}
  <ul>
    <!-- {% load tz %}
    {% localtime on %} -->
    {% for lesson in lesson_list %}
      {% if lesson.recording %}
      <li>
        <a href="{{ lesson.get_absolute_url }}">{{ lesson.student }}'s lesson - {{ lesson.date_and_time }}</a> (Teacher: {{lesson.teacher}})
      </li>
      {% elif lesson.recording_processing_filestorage_name in ALL_PROCESSES %}
      <li>
        <a style="color:Orange" href="{{ lesson.get_absolute_url }}">{{ lesson.student }}'s lesson - {{ lesson.date_and_time }}</a> (Teacher: {{lesson.teacher}})
      </li>
      {% else %}
      <li>
        <a style="color:Tomato" href="{{ lesson.get_absolute_url }}">{{ lesson.student }}'s lesson - {{ lesson.date_and_time }}</a> (Teacher: {{lesson.teacher}})
      </li>
      {% endif %}
      <!-- type instead: lesson.date_and_time|localtime -->
    {% endfor %}
    <!-- {% endlocaltime %} -->
  </ul>
  {% else %}
    <p>There are no lessons in the archive.</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/lesson_update_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/student_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Student</h1>

{% if error %}
  <p class="error">{{ error }}</p>
    <a href="{% url 'students' %}">
      <input type="submit" value="Understood.">
    </a>

{% else %}
  <p>Are you sure you want to delete the student: {{ student }}?</p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete.">
  </form>

{% endif %}
{% endblock %}

catalog/templates/catalog/student_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="hidden" name="next" value="{{ request.GET.next }}">
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/student_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Student List</h1>
  <hr>
  {% if perms.catalog.add_student %}
  <h2>Staff: <a href="{% url 'student-create' %}" class="btn btn-success">Add New Student</a></h2>
  <hr>
  {% endif %}
  {% if student_list %}
  <ul>
    {% for student in student_list %}
      <li>
        <a href="{{ student.get_absolute_url }}">{{ student.name }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no students in the archive.</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/tag_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="hidden" name="next" value="{{ request.GET.next }}">
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/tag_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Lesson Tag List</h1>
  <hr>
  {% if perms.catalog.add_tag %}
  <h2>Staff: <a href="{% url 'tag-create' %}" class="btn btn-success">Add New Tag</a></h2>
  <hr>
  {% endif %}
  {% if tag_list %}
  <ul>
    {% for tag in tag_list %}
      <li>
        <p>{{ tag.name }}</p>
        {% if perms.catalog.change_tag and perms.catalog.delete_tag %}
          <a href="{% url 'tag-update' tag.id %}" class="btn btn-success btn-sm">Edit Text</a>
          <a href="{% url 'tag-delete' tag.id %}" class="btn btn-danger btn-sm">Delete</a>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no lesson tags in the archive.</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/teacher_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Teacher</h1>

{% if error %}
  <p class="error">{{ error }}</p>
    <a href="{% url 'teachers' %}">
      <input type="submit" value="Understood.">
    </a>

{% else %}
  <p>Are you sure you want to delete the teacher: {{ teacher }}?</p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete.">
  </form>

{% endif %}
{% endblock %}

catalog/templates/catalog/teacher_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Teacher List</h1>
  <hr>
  {% if perms.catalog.add_teacher %}
  <h2>Staff: <a href="{% url 'teacher-create' %}" class="btn btn-success">Add New Teacher</a></h2>
  <hr>
  {% endif %}
  {% if teacher_list %}
  <ul>
    {% for teacher in teacher_list %}
      <li>
        <p>{{ teacher.name }}</p>
        {% if perms.catalog.change_teacher and perms.catalog.delete_teacher %}
          <a href="{% url 'teacher-update' teacher.id %}" class="btn btn-success btn-sm">Edit Name</a>
          <a href="{% url 'teacher-delete' teacher.id %}" class="btn btn-danger btn-sm">Delete</a>
        {% endif %}
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no teachers in the archive.</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/type_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="hidden" name="next" value="{{ request.GET.next }}">
    <input type="submit" value="Submit">
  </form>
{% endblock %}